# Site settings
title: Masaki Wakatake
description: Simple is best. There is no place like home.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Masaki Wakatake
user_description: It works! :)
user_title: Hyper Media Creater lol
email: masaki@w-k-t-k.com
twitter_username: mwktk2
facebook_username: masaki.wakatake
github_username:  GATAKAWAKACHICO
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-50860585-11"

exclude: ['package.json','src','node_modules']
